##############################
# Development Docker Compose #
##############################

# This is the version of the Docker Compose standard
version: '3.4'

services:
  # The website is the landing page for the CC Vocabulary project
  website:
    # Name of the container
    container_name: vocabulary-website
    # Use the CC Vocabulary image
    image: ccvocabulary:latest
    # Restart build if it fails
    restart: always
    # If the image is not found, build it
    build: .

    # The command to run in the container
    command: npm run serve:website

    # Volumes attached to the container
    volumes:
      # Enable code changes to reflect in the container
      - .:/codebase
      # Ensures that host node_modules are not mounted
      - node_modules:/codebase/node_modules
    ports:
      # Map 8080 in the container to the same port on the host
      - 8080:8080

  storybook:
    # Name of the container
    container_name: vocabulary-storybook
    # Use the CC Vocabulary image
    image: ccvocabulary:latest
    # Restart build if it fails
    restart: always
    # If the image is not found, build it
    build: .

    # The command to run in the container
    command: npm run serve:storybook
    
    # Volumes attached to the container
    volumes:
      - .:/codebase
      - node_modules:/codebase/node_modules
    ports:
      # Map 6006 in the container to the same port on the host
      - 6006:6006

volumes:
  # Holds the node_modules directory
  # Prevents the host node_modules from being mounted and used
  node_modules:
